import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/context/userContext";

import { NextUIProvider } from "@nextui-org/react";
import SideBar from "./admin/sidebar";
import { SideBarProvider } from "@/context/sideBarContext";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
     return (
    <AuthProvider>
      <SideBarProvider>
      <html lang="en" foxified=""
      className="antialiased"
      suppressHydrationWarning={true}
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          
          <NextUIProvider>{children}</NextUIProvider>
        </body>
      </html>
      </SideBarProvider>
    </AuthProvider>
  );
}
